### ISSUE TITLE
DAESRV upgrade to AlmaLinux 9

### ISSUE THREAD

**Issue by awattsFNAL** [fermi-ad/controls#18]

**Comment by awattsFNAL** [comment]
From Larry:

> Host daesrv2 has been updated to AlmaLinux 9 – please feel free to test anything you’d like.   I haven’t tried all the webserver cgi-bin scripts yet,  but some worked, so the web-server is basically sane.
 
I like to plan for a switchover next week if all testing looks good.

**Comment by awattsFNAL** [comment]
Proposed date is 0900-1000 Tuesday Oct. 17. From Larry:

> Servers and services impacted:
 
> All java engines (dce, due, dse, dpe servers):  All services stopped – e.g. DAEs, OACS, DPM, etc..
> Elog servers elog1,elog2: remote file systems unavailable
> Java app servers (appsrv1-4): remote file systems unavailable
> Samba servers (ad-c-samba, ad-c-samba-3): remote file systems unavailable

**Comment by awattsFNAL** [comment]
At request of FAST/IOTA (NML) and PIP-2IT folks, we've rescheduled to 10/25/23 @0900.

**Comment by finstrom** [comment]
This is complete.
